version: "3.7"
services:
  sendpoints:
    image: serenalovedavid/walkabilityswarm:sendpoints
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 2048M
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: /mnt/sharedfolder/output/
        target: /app/src/main/java/org/mccaughey/output/
      - type: bind
        source: /home/ubuntu/.m2
        target: /root/.m2
  sendpolygon:
    image: serenalovedavid/walkabilityswarm:sendpolygon
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 4096M
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: /mnt/sharedfolder/output/
        target: /app/src/main/java/org/mccaughey/output/
      - type: bind
        source: /home/ubuntu/.m2
        target: /root/.m2
  sendconnectivity:
    image: serenalovedavid/walkabilityswarm:sendconnectivity
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 2048M
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: /mnt/sharedfolder/output/
        target: /app/src/main/java/org/mccaughey/output/
      - type: bind
        source: /home/ubuntu/.m2
        target: /root/.m2
  senddensity:
    image: serenalovedavid/walkabilityswarm:senddensity
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 2048M
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: /mnt/sharedfolder/output/
        target: /app/src/main/java/org/mccaughey/output/
      - type: bind
        source: /home/ubuntu/.m2
        target: /root/.m2
  sendlum:
    image: serenalovedavid/walkabilityswarm:sendlum
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 2048M
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: /mnt/sharedfolder/output/
        target: /app/src/main/java/org/mccaughey/output/
      - type: bind
        source: /home/ubuntu/.m2
        target: /root/.m2
  sendzscore:
    image: serenalovedavid/walkabilityswarm:sendzscore
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 2048M
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: /mnt/sharedfolder/output/
        target: /app/src/main/java/org/mccaughey/output/
      - type: bind
        source: /home/ubuntu/.m2
        target: /root/.m2
