apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sendlum
  name: sendlum
spec:
  containers:
    - image: serenalovedavid/walkabilityswarm:sendlum
      name: sendlum
      resources:
        limits:
          cpu: 100m
          memory: "512000000"
      volumeMounts:
        - mountPath: /app/src/main/java/org/mccaughey/output/
          name: sendlum-hostpath0
        - mountPath: /root/.m2
          name: sendlum-hostpath1
  restartPolicy: OnFailure
  volumes:
    - hostPath:
        path: /mnt/sharedfolder/output
      name: sendlum-hostpath0
    - hostPath:
        path: /home/ubuntu/.m2
      name: sendlum-hostpath1
status: {}